ns-train depth-nerfacto \
    --data ../dataset/images_and_cams/DayaTemple/image_scaled/train.json \
    --pipeline.model.log2-hashmap-size 19 \
    --pipeline.model.hidden-dim 64 \
    --pipeline.model.distortion-loss-mult 0.02 \
    --pipeline.model.depth-loss-mult 0.02 \
    --pipeline.model.num-nerf-samples-per-ray 48 \
    --pipeline.model.orientation-loss-mult 0.0001 \
    --pipeline.model.proposal-update-every 4 \
    --pipeline.model.predict-normals True \
    --pipeline.model.collider-params near_plane 0.1 far_plane 10.0 \
    --pipeline.model.depth-loss-type URF \
    --pipeline.model.starting-depth-sigma 0.1 \
    --pipeline.model.background-color random